apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: saas-docs
  namespace: saas-docs
spec:
  parentRefs:
    - name: gateway-external
      namespace: gateway-api
      sectionName: https-docs-audithub
  hostnames:
    - docs.audithub.dev
  rules:
    - matches:
        - path:
            type: PathPrefix
            value: /
      backendRefs:
        - name: saas-docs
          port: 80