name: K8S-Deploy Veridise Docs
run-name: Kubernetes deployment for Veridise Docs
on:
  # Allows you to run this workflow manually from the Actions tab or via the api
  workflow_call:
    inputs:
      environment:
        description: "Environment to use"
        required: true
        type: string
  
jobs:
  deploy-docs:
    runs-on: ${{ inputs.environment == 'production' && 'prod-saas-docs' || inputs.environment }}
    environment:
      name: ${{ inputs.environment }}
      url: ${{ vars.ROOT_URL }}
    timeout-minutes: 10
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3

      - name: Setup kubectl
        uses: azure/setup-kubectl@v3.1

      - name: Deploy
        run: kubectl apply -k deployment/kubernetes/overlays/${{ inputs.environment }}/ &&
          kubectl rollout restart deployment saas-docs -n saas-docs
